name: fastgui
channels:
- pytorch
- defaults
dependencies:
- fastai2==0.0.15
- jupyter
- pytorch>=1.3.0
- torchvision>=0.5
- matplotlib
- pandas
- requests
- pyyaml
- fastprogress>=0.1.22
- pillow
- python>=3.6
- pip
- scikit-learn
- scipy
- spacy
- voila
- ipywidgets
